### PR TITLE
Update of README and both startup scripts

### LINKED ISSUE #2: Modify repository name and readme according to our project
Project repository needs modification in terms of repo name, readme and other

### PR DESCRIPTION
**Pull request by amarbajric**
resolves #2 

**DONE:**

- Updated `README.md`.
  - General info added for repo and the intention of the fork
  - Added instructions on how to set-up docker container for mysql
  - Added instructions on how to execute all services by using either the `start.bat` or `start.sh` scripts
  - Explained how to enable/disable the example processes which were discussed in the PR #54.
  - Added further description and instructions on how to completely enable/disable the example processes.
- Adapted the `start.sh` and `start.bat` scripts:
  - Both scripts now support dev mode or normal mode. This allows for skipping the execution of the `ConfigurationService` to use the example processes.

**ToDo:**
- @loete Please test the `start.sh` script on Linux with dev mode and without dev mode
  - Disabling dev mode (i.e. running the normal mode) does not require any arguments.
- @tortmann Please test the `start.bat` script on Windows with dev mode and without dev mode (normal mode) 

> Read README in the associated branch for further information.

### CODE REVIEW

**Review by tortmann — CHANGES_REQUESTED** [review]
### 1) Installation of Docker container worked!
(small issue at first execution - `Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection` - which was solved for me by restarting docker, other fixes can be found here:
<https://github.com/docker/for-win/issues/611>)

##### please add to readme for reference

### 2) starting services on WINDOWS - kinda worked
execution of `start.bat` should NOT be made as administrator on windows since it throws an error because the other scripts cannot be executed as admin by the first script (probably the reason) 

##### please add to readme

`start.bat` execution works (in non-admin mode) both in normal and dev mode. HOWEVER starting the Execution Platform as described in the readme does not work for me. (even if done in the exact order as mentioned in the readme) the same thing happens(nothing) when starting the modelling platform via `gradlew bootRun`

the alternative - running the .jar files works fine for the modellingplatform. 

restarts of docker and the pc did not change to outcome of trying to start theMplatform and GUI via the start.bat script.

**Comment by amarbajric** [comment]
**1.)**

> please add to readme for reference

I would highly advise against putting solutions and other references referring to errors, issues and workarounds for used technologies, libraries or frameworks in the README. As there can occur numerous errors on different operating systems, it should be avoided.
Also to mention, that this issue did not occur on my machine (macOS 12.6), nor on a Linux(Ubuntu) set-up. The associated docker installations can be found here #36. 
- Is this advice understandable or can it be confirmed? Open for other opinions.

**2.)**

> execution of start.bat should NOT be made as administrator on windows since it throws an error because the other scripts cannot be executed as admin by the first script (probably the reason)
> 
> please add to readme

I have updated the README and added a hint, where the execution of the `start.bat` with admin privileges is not recommended.

> HOWEVER starting the Execution Platform as described in the readme does not work for me. (even if done in the exact order as mentioned in the readme) the same thing happens(nothing) when starting the modelling platform via gradlew bootRun

If you refer to the manual execution, where all services are started manually, I can confirm that the manual execution is working on macOS 12.6 without any problems. I can also confirm, that at the beginning of the project, the manual execution worked on my windows machine. Can you provide further steps on how you tried to execute the services manually and what the output was (if any generated)?

**Comment by tortmann** [comment]
1)
>I would highly advise against putting solutions and other references referring to errors, issues and workarounds for used technologies, libraries or frameworks in the README

you are definitely correct about that and we should rather include this in our internal documentation. this issue will most likely only occur on some windows machines. thank you very much for the suggestion.

2)
>I have updated the README and added a hint

Thank you!

>Can you provide further steps on how you tried to execute the services manually and what the output was (if any generated)?

##### I executed `start.bat` in both modes and get the following result in the main shell

```javascript
Start ProcessModelStorage
##########################################################


##########################################################
Start Gateway
##########################################################


##########################################################
Start ProcessEngine
##########################################################


##########################################################
Start ExternalCommunicator
##########################################################


##########################################################
Start EventLogger
##########################################################


##########################################################
Start GUI
##########################################################


##########################################################
Start ModellingPlatform
##########################################################


##########################################################
Installation and boot finished
##########################################################

Drücken Sie eine beliebige Taste . . .
```

##### Additionally the individual command shells opened for each script that was executed like so:

```javascript
Start Gateway
##########################################################

Drücken Sie eine beliebige Taste . . .
```

##### When navigating to http://localhost:3000 as instructed I can not establish a connection (Firefox, Chrome, IE)

Furthermore I executed each script manually (in the order mentioned in the `readme`) and got the same result - no connection to `localhost:3000` or `localhost:4000` (when executing this respective script for the Modelling Platform)

However when I run the `.jar files` by using the command in the readme `java -jar ModellingPlatform-0.0.1-SNAPSHOT.jar` Spring starts up as expected and I have access to the S-BPM Modeller.

image


image

Do you have any suggestions what I should do differently or what you did differently when you executed it on windows?

**Comment by amarbajric** [comment]
@tortmann 

I have switched to my windows machine in order to check back on your issues. Here are the results.

## 1.) Docker mysql container set-up

- Changed into the directory where the `docker-compose.yml` file resides
- Started the command `docker-compose up`
- Building the image + starting the container was successful and finished without any error.
```
$ docker-compose up
Creating network "mysqldocker_default" with the default driver
Building mysql
Step 1/5 : FROM mysql:latest
latest: Pulling from library/mysql
Digest: sha256:691c55aabb3c4e3b89b953dd2f022f7ea845e5443954767d321d5f5fa394e28c
Status: Downloaded newer image for mysql:latest
 ---> 5195076672a7
Step 2/5 : MAINTAINER Bajric (amar.bajric@edu.fh-joanneum.at)
 ---> Running in 1043d5aef4f9
Removing intermediate container 1043d5aef4f9
 ---> 1c0586d7fc47
Step 3/5 : ENV MYSQL_ROOT_PASSWORD="Pa$$w0rd"
 ---> Running in 14e9d765cf3f
Removing intermediate container 14e9d765cf3f
 ---> e56c9bf9b5ab
Step 4/5 : RUN apt-get update
```
This output is truncated.

## 2.) Execution of all services with `start.bat` (Windows)
- Go to the `/Setup/start_windows` directory
- Double click on the `start.bat` (start without admin privileges)
- Choose dev mode
- All services started (see picture below)
image

**NO** service has thrown any errors. All services ran without any problems and I was also able to access the platform and the modeler.

It seems like these issues are (at the moment) related to your machine and set-up/configuration.

**Suggestions:**
- Delete repository locally and clone again
- Update Docker or remove + install again
- reinstall Java? (idk if Java could cause these issues)
- start the `start.bat` again **AND** wait for 2-5 min. Maybe the services need some time to start up on your machine?

**Comment by tortmann** [comment]
Thank you for the feedback I will try again on a different machine aswell. I do not get any startup(loading) feedback after start.sh has executed in the individual shells for a yet unknown reason. I will provide feedback after I implemented all your suggestions. (I do not get any errors either however - that is why I didn't post any) 

>reinstall Java? (idk if Java could cause these issues)

shouldn't be the problem since running the .jar files works just fine

##### I will keep you updated

**Comment by tortmann** [comment]
I followed the same procedure on my laptop and now it works like it's supposed to. I will try to troubleshoot the issue on the other pc tomorrow to see what is causing it since it may be relevant for other windows users

**Comment by amarbajric** [comment]
Very good!
As @loete  is not available this week, I would appreciate if you could approve the changes made in this PR.
Tab `Files Changed` > Click on `Review Changes` > Select Radio Button `Approve` > `Submit`.
You can also merge it then, by clicking on `Squash and merge`.
Deleting the branch is not necessary as it will be done at a later stage during the project.

**Review by tortmann — APPROVED** [review]
Forgot to approve changes yesterday at night. Will investigate the issue on the other pc further for future reference.

**Pull request merged**
